### ISSUE TITLE
ICE Perspective is missing

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#127]
The ICE Perspective no longer appears in the unstable nightly executables.

**Comment by jayjaybillings** [comment]
It worked for me. Did you try with a clean workspace?

Jay

From my phone.
________________________________
From: SmithRWORNL
Sent: Wednesday, February 24, 2016 4:00 PM
To: eclipse/ice
Subject: [ice] ICE Perspective is missing (#127)



The ICE Perspective no longer appears in the unstable nightly executables.

-

**Comment by SmithRWORNL** [comment]
@jayjaybillings 

Yes, it was under a clean workspace, in both Windows and Linux.

**Comment by jayjaybillings** [comment]
Okay. On it. Building now.

**Comment by jayjaybillings** [comment]
This works just fine for me. I built ICE from scratch, completely removed everything from my workspace and launched it. No problems either finding the perspective or creating Items. Please submit a screenshot showing it missing from the list.

**Comment by SmithRWORNL** [comment]
![iceperspectivemissing](https://cloud.githubusercontent.com/assets/12715269/13302588/93fd328e-db18-11e5-8a58-ef605ee78950.png)

I haven't tried building from next, only downloading the products from the update site, so it may be a problem with Habilis.

**Comment by SmithRWORNL** [comment]
![itemwizardmissing](https://cloud.githubusercontent.com/assets/12715269/13302683/2defeb52-db19-11e5-96db-cdfb9c337547.png)

Tried to create a item from the New button, button the Create Item Wizard is also missing.

**Comment by arbennett** [comment]
I just downloaded the unstable nightly for Linux x86_64 and have these issues.  Building from source does not have these issues for me either.

**Comment by jayjaybillings** [comment]
I just downloaded the nightly and also got the same problem. Looking into it now.

**Comment by jarrah42** [comment]
I notice that next no longer includes org.eclipse.ice.client.rcp in the org.eclipse.ice.feature. I've re-added it in my workspace because it contains the splash.bmp, but it may also be why you're not seeing the perspective.

**Comment by jayjaybillings** [comment]
I just committed a fix to the feature. Good catch.

The org.eclipse.ice.io bundle is not resolving because it is depending on the org.eclipse.ice.dependencies bundle, which doesn't exist in next and isn't part of the feature. You can see this if you check the OSGi console.

The org.eclipse.ice.dependencies bundle does exist in master. I suspect that the product is being resolved against the version from the master and not the version in next. I have put a fix into the build that should take care of this. Please try the nightly in the morning.

**Comment by SmithRWORNL** [comment]
Just tried the latest unstable nightly for Windows, and it's still missing the perspective.

**Comment by jayjaybillings** [comment]
Okay. I'm looking into it. Thanks for checking it!

**Comment by jayjaybillings** [comment]
Interestingly, this is not a problem with the 'next' build from our HIPP, http://hudson.eclipse.org/ice.

**Comment by jayjaybillings** [comment]
I have fixed this and confirmed it on both Habilis and my desktop. Please try it for yourself.
