### ISSUE TITLE
Installing from the P2 site is broken

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#190]
Jay Jay,

You gave me incomplete instructions...

Cannot complete the install because one or more required items could not be found.
  Software being installed: ICE Infrastructure Feature 2.1.8.201604122238 (org.eclipse.ice.feature.group 2.1.8.201604122238)
  Missing requirement: EAVP Datastructures 2.1.8.201604082008 (org.eclipse.eavp.viz.datastructures 2.1.8.201604082008) requires 'bundle org.eclipse.nebula.visualization.widgets 1.0.0' but it could not be found
  Cannot satisfy dependency:
    From: BatteryML 2.1.8.201604122238 (org.eclipse.ice.caebat.batml 2.1.8.201604122238)
    To: bundle org.eclipse.ice.datastructures 0.0.0
  Cannot satisfy dependency:
    From: ICEDataStructures 2.1.8.201604122238 (org.eclipse.ice.datastructures 2.1.8.201604122238)
    To: package org.eclipse.eavp.viz.datastructures.VizObject 0.0.0
  Cannot satisfy dependency:
    From: ICE Infrastructure Feature 2.1.8.201604122238 (org.eclipse.ice.feature.group 2.1.8.201604122238)
    To: org.eclipse.ice.caebat.batml [2.1.8.201604122238]

First I had to install the Nebula project from http://download.eclipse.org/technology/nebula/snapshot
This let me install EAVP, but not ICE from the repository you provided:

Cannot complete the install because one or more required items could not be found.
  Software being installed: ICE Infrastructure Feature 2.1.8.201604122238 (org.eclipse.ice.feature.group 2.1.8.201604122238)
  Missing requirement: Client 2.1.8.201604122238 (org.eclipse.ice.client 2.1.8.201604122238) requires 'bundle com.sun.jersey 1.17.0' but it could not be found
  Cannot satisfy dependency:
    From: ICE Infrastructure Feature 2.1.8.201604122238 (org.eclipse.ice.feature.group 2.1.8.201604122238)
    To: org.eclipse.ice.client [2.1.8.201604122238]

Although I found and downloaded http://repo1.maven.org/maven2/com/sun/jersey/jersey-archive/1.19.1/jersey-archive-1.19.1.zip and http://repo1.maven.org/maven2/com/sun/jersey/jersey-archive/1.17/jersey-archive-1.17.zip, I don't know how to make this available under Eclipse. 
Can you give me instructions?
What else is required for installing ICE?
I have installed Eclipse through the PTP environment which has C++ and Fortran but not Java. Should I install the Java environment for this?

Thanks
Norbert

**Comment by jayjaybillings** [comment]
Submitted by @pnorbert via ORNL eclipse-ug list.

**Comment by jayjaybillings** [comment]
Looks like this is caused by the category.xml file. I'm working on it now to refer to the EAVP update site instead of publishing the version in the target platform as part of ICE's p2 site.

**Comment by jayjaybillings** [comment]
This turns out to be a regression based on some recent changes that Greg made to avoid including other non-ICE bundles in the p2 repository. He's going to take this bug from here.

**Comment by jarrah42** [comment]
The nebula and EAVP repos should now be automatically added. Provided the user has the "Contact all update sites..." option selected,  this should now work as expected.

**Comment by chaffra** [comment]
Hi,
I am still encountering the same problem with jersey missing. Where should I install jersey from? I am trying to install the latest ICE from  http://mirror.cc.columbia.edu/pub/software/eclipse/ice/builds/next/
Any suggestion is appreciated. Thanks.

> Cannot complete the install because one or more required items could not be found.
  Software being installed: ICE Infrastructure Feature 2.2.0.201705261546 (org.eclipse.ice.feature.group 2.2.0.201705261546)
  Missing requirement: Client 2.2.0.201705261546 (org.eclipse.ice.client 2.2.0.201705261546) requires 'bundle com.sun.jersey 1.17.0' but it could not be found
  Cannot satisfy dependency:
    From: ICE Infrastructure Feature 2.2.0.201705261546 (org.eclipse.ice.feature.group 2.2.0.201705261546)
    To: org.eclipse.ice.client [2.2.0.201705261546]

**Comment by jayjaybillings** [comment]
@jarrah42 Can you look at this?

I just merged 2.2.1 into next and will merge the updates into master soon.
