### ISSUE TITLE
ICE Next MeshComponent fails to import MeshDescription

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#202]
I just updated to the latest in ICE next and resolved and reset the target (so it should have updated EAVP bundles).

I have a build error in MeshComponent saying that MeshDescription from viz.service.mesh.datastructures cannot be resolved. 

Am I the only one? This is with just ICE plugins in the workspace, no EAVP bundles.

**Comment by jayjaybillings** [comment]
I fixed this over the weekend. It works for me on both of my machines. Make sure that you "Reload" your target.

**Comment by jarrah42** [comment]
I have the error also. I tried reloading the target and rebuilding the plugin but the error persists...

**Comment by jarrah42** [comment]
Fixed now. I have the eavp plugins in my workspace, so I had to update them also.

**Comment by amccaskey** [comment]
I got it fixed without any eavp plugins in my workspace. Reloading the target didn't work immediately, had to delete the repo for some reason, clone it again, and load the target. Error gone.

**Comment by SmithRWORNL** [comment]
It seems that everyone now has a working version of the test and that a newly cloned instance will build. Can we consider this resolved and close the issue?

**Comment by jayjaybillings** [comment]
I had to explicitly hit the "reload" button in the target editor so that it downloaded the latest bundles, but that fixed it for me.

**Comment by amccaskey** [comment]
So this is fixed. Closing.
